### ISSUE TITLE
Conversion issue

### ISSUE THREAD

**Issue by NBPalstrom** [SchweppeLab/DBKey#28]
Hello, 

As mentioned in the email, I have an issue when I try to convert my own spectral library in .sptxt to .db using DBKey. I am using the docker image, which works fine with the example files you have provided. I have attached a shortened version of the library I have created, which I confirmed to also not work. I have also tried running the Shiny app locally, which throws the following error: 

"Warning: Error in : BiocParallel errors
2 remote errors, element index: 1, 9 
13 unevaluated and other errors
first remote error: 
Error in str_split(remove_modstring, "/", simplify = T)[, 1]: subscript out of bounds"

Any assistance you can provide would be greatly appreciated!

Best regards, 
Nicolai

[SpecLib_shortened.zip](https://github.com/SchweppeLab/DBKey/files/10801278/SpecLib_shortened.zip)

**Comment by mammmals** [comment]
Hi @NBPalstrom, looks like this may be a string read bug here: https://github.com/SchweppeLab/DBKey/blob/c46c1bc2b74a37db62571aeca27c501234254eef/lib/LibraryParserv2.R#L193

We'll look into it!

**Comment by ChrisMcGann** [comment]
Was an issue with the handling of unmodified peptides, should be fixed now. Let me know if it's working for you
